object Versions {
    const val GRADLE = "7.2.0"
    const val KOTLIN = "1.7.0"
    const val JAVA = "1.8"
    const val CORE_KTX = "1.8.0"
    const val CORE_FRAGMENT_KTX = "1.4.1"
    const val APPCOMPAT = "1.4.2"
    const val MATERIAL = "1.6.1"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val NAVIGATION = "2.4.2"
    const val HILT = "2.42"
    const val RETROFIT = "2.9.0"
    const val HTTP_LOGGER = "4.9.3"
    const val SERIALIZATION = "1.3.2"
    const val SERIALIZATION_CONVERTER = "0.8.0"
    const val GOOGLE_SERVICES = "4.3.10"
    const val FIREBASE_BOM = "30.1.0"
}
